import { NextRequest, NextResponse } from "next/server";
import { sql } from "drizzle-orm";
import { getDb } from "../../../db";
import { getPanelUserFromRequest } from "../../../lib/panelAuth";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
let ready=false; async function ensureTable(db:ReturnType<typeof getDb>){if(ready)return;await db.execute(sql`create table if not exists public.map_routes (id serial primary key,owner_id text not null,name text not null,description text,waypoints_json text not null,created_at text not null default CURRENT_TIMESTAMP::text,updated_at text not null default CURRENT_TIMESTAMP::text)`);await db.execute(sql`create index if not exists idx_map_routes_owner_id on public.map_routes(owner_id,id)`);await db.execute(sql`alter table public.map_routes enable row level security`);ready=true;}
function cleanPoints(v:unknown){if(!Array.isArray(v))return [];return v.slice(0,100).map((p:any,i)=>({order:i+1,latitude:Number(p?.latitude),longitude:Number(p?.longitude)})).filter(p=>Number.isFinite(p.latitude)&&Number.isFinite(p.longitude)&&Math.abs(p.latitude)<=90&&Math.abs(p.longitude)<=180);}
export async function GET(req:NextRequest){const u=await getPanelUserFromRequest(req);if(!u)return NextResponse.json({error:"Unauthorized"},{status:401});const db=getDb();await ensureTable(db);const r:any=await db.execute(sql`select id,name,description,waypoints_json,created_at,updated_at from public.map_routes where owner_id=${u.id} order by id desc limit 100`);return NextResponse.json({routes:Array.from(r as any).map((x:any)=>({id:x.id,name:x.name,description:x.description||"",waypoints:JSON.parse(x.waypoints_json||"[]"),createdAt:x.created_at,updatedAt:x.updated_at}))});}
export async function POST(req:NextRequest){const u=await getPanelUserFromRequest(req);if(!u)return NextResponse.json({error:"Unauthorized"},{status:401});const db=getDb();await ensureTable(db);const b=await req.json().catch(()=>({}));const pts=cleanPoints(b?.waypoints);if(!pts.length)return NextResponse.json({error:"Adicione pelo menos um ponto à rota."},{status:400});const name=String(b?.name||"Rota").trim().slice(0,60)||"Rota";const description=String(b?.description||"").trim().slice(0,240);const now=new Date().toISOString();const id=Number(b?.id);if(Number.isFinite(id)&&id>0){const r:any=await db.execute(sql`update public.map_routes set name=${name},description=${description},waypoints_json=${JSON.stringify(pts)},updated_at=${now} where id=${id} and owner_id=${u.id} returning id`);if(!Array.from(r as any).length)return NextResponse.json({error:"Rota não encontrada."},{status:404});return NextResponse.json({ok:true,id});}const r:any=await db.execute(sql`insert into public.map_routes(owner_id,name,description,waypoints_json,created_at,updated_at) values(${u.id},${name},${description},${JSON.stringify(pts)},${now},${now}) returning id`);return NextResponse.json({ok:true,id:(Array.from(r as any)[0] as any)?.id});}
export async function DELETE(req:NextRequest){const u=await getPanelUserFromRequest(req);if(!u)return NextResponse.json({error:"Unauthorized"},{status:401});const db=getDb();await ensureTable(db);const id=Number(req.nextUrl.searchParams.get("id"));if(!Number.isFinite(id)||id<=0)return NextResponse.json({error:"Rota inválida."},{status:400});await db.execute(sql`delete from public.map_routes where id=${id} and owner_id=${u.id}`);return NextResponse.json({ok:true});}
