import jsPDF from "jspdf";

const C={navy:[4,32,39] as [number,number,number],teal:[31,207,160] as [number,number,number],panel:[8,48,55] as [number,number,number],panel2:[11,61,68] as [number,number,number],white:[246,255,252] as [number,number,number],muted:[145,190,194] as [number,number,number],blue:[75,190,235] as [number,number,number],violet:[185,145,255] as [number,number,number]};
const n=(v:any,d=1)=>{const x=Number(v);return Number.isFinite(x)?x.toLocaleString("pt-BR",{minimumFractionDigits:d,maximumFractionDigits:d}):"—"};
const mph=(v:any)=>{const x=Number(v);return Number.isFinite(x)?n(x/1.609344,2):"—"};
const date=(v:any)=>{if(!v)return "—";const d=new Date(String(v).length===10?`${v}T12:00:00`:v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString("pt-BR",{weekday:"short",day:"2-digit",month:"2-digit",hour:String(v).includes("T")?"2-digit":undefined,minute:String(v).includes("T")?"2-digit":undefined})};
function pos(lat:number,lon:number){const p=(v:number,s:string)=>{const a=Math.abs(v),g=Math.floor(a),m=(a-g)*60;return `${g}° ${m.toFixed(2)}' ${s}`};return `${p(lat,"S")}  ·  ${p(lon,"W")}`}
function txt(doc:jsPDF,t:string,x:number,y:number,size=10,bold=false,color:C['white']|[number,number,number]=C.white){doc.setFont("helvetica",bold?"bold":"normal");doc.setFontSize(size);doc.setTextColor(...color);doc.text(t,x,y)}
function card(doc:jsPDF,x:number,y:number,w:number,h:number,label:string,value:string,detail:string,color:[number,number,number]=C.teal){doc.setFillColor(...C.panel);doc.roundedRect(x,y,w,h,4,4,"F");doc.setDrawColor(...color);doc.setLineWidth(.7);doc.line(x+4,y+4,x+4,y+h-4);txt(doc,label,x+9,y+9,7,true,C.muted);txt(doc,value,x+9,y+20,15,true,C.white);txt(doc,detail,x+9,y+h-7,7,false,C.muted)}
function header(doc:jsPDF,data:any,subtitle:string){doc.setFillColor(...C.navy);doc.rect(0,0,297,32,"F");doc.setFillColor(...C.teal);doc.rect(0,0,6,32,"F");txt(doc,"PAINEL DE BORDO",14,12,16,true);txt(doc,subtitle,14,21,9,true,C.teal);txt(doc,pos(Number(data?.position?.lat||0),Number(data?.position?.lon||0)),283,12,9,true,C.white);txt(doc,data?.position?.geography?.label||"Previsão oceânica",283,21,7,false,C.muted)}
function footer(doc:jsPDF){const pages=doc.getNumberOfPages();for(let i=1;i<=pages;i++){doc.setPage(i);doc.setDrawColor(...C.teal);doc.line(12,198,285,198);txt(doc,"Dados modelados para apoio operacional. Não usar como referência única de navegação.",12,203,6,false,[80,110,114]);txt(doc,`Página ${i}`,285,203,6,false,[80,110,114])}}
export function createPositionForecastPdf(data:any){const doc=new jsPDF({orientation:"landscape",unit:"mm",format:"a4"});header(doc,data,"PREVISÃO OCEÂNICA · VENTO · MAR · CORRENTE · CLOROFILA");txt(doc,"CONDIÇÕES AGORA",14,42,8,true,[35,100,103]);const cur=data?.current||{};const cards:any[]=[["VENTO",`${n(cur.windSpeedKmh,0)} km/h`,`${cur.windDirection||"—"} · rajadas ${n(cur.gustKmh,0)} km/h`,C.teal],["ONDA",`${n(cur.waveHeightM)} m`,`${cur.waveDirection||"—"} · período ${n(cur.wavePeriodS)} s`,C.blue],["CORRENTE",`${mph(cur.currentKmh)} mph`,`${cur.currentDirection||"—"} · ${n(cur.currentDirectionDeg,0)}°`,C.violet],["TEMP. MAR",`${n(cur.seaTemperatureC)} °C`,`Superfície`,[245,176,65]],["CLOROFILA-A",`${n(cur.chlorophyllMgM3,2)} mg/m³`,`VIIRS · leitura atual`,[75,220,145]]];cards.forEach((c,i)=>card(doc,14+i*54.5,47,50.5,38,c[0],c[1],c[2],c[3]));txt(doc,"PRÓXIMOS 7 DIAS",14,96,10,true,[35,100,103]);const weekly=Array.isArray(data?.weeklyForecast)?data.weeklyForecast.slice(0,7):[];weekly.forEach((d:any,i:number)=>{const x=14+i*39.1;doc.setFillColor(...(i%2?C.panel:C.panel2));doc.roundedRect(x,101,35.5,77,4,4,"F");txt(doc,date(d.date).replace(/,.*$/,""),x+4,111,8,true,C.teal);txt(doc,"VENTO",x+4,121,6,true,C.muted);txt(doc,`${n(d.windSpeedKmh,0)} km/h`,x+4,129,11,true);txt(doc,`Raj. ${n(d.gustKmh,0)}`,x+4,135,6,false,C.muted);txt(doc,"ONDA",x+4,145,6,true,C.muted);txt(doc,`${n(d.waveHeightM)} m`,x+4,153,11,true);txt(doc,"CLOROFILA",x+4,163,6,true,[100,230,170]);txt(doc,`${n(d.chlorophyllMgM3,2)} mg/m³`,x+4,171,9,true)});txt(doc,`Emitido em ${new Date().toLocaleString("pt-BR")}`,283,190,7,false,[80,110,114]);const forecast=Array.isArray(data?.forecast)?data.forecast:[];for(let start=0;start<forecast.length;start+=8){doc.addPage();header(doc,data,"PREVISÃO POR HORÁRIO · CARDS OPERACIONAIS");forecast.slice(start,start+8).forEach((d:any,i:number)=>{const col=i%4,row=Math.floor(i/4),x=14+col*68.2,y=42+row*73;doc.setFillColor(...C.panel);doc.roundedRect(x,y,63.5,64,4,4,"F");txt(doc,date(d.time),x+5,y+9,8,true,C.teal);txt(doc,"VENTO",x+5,y+19,6,true,C.muted);txt(doc,`${n(d.windSpeedKmh,0)} km/h`,x+5,y+28,13,true);txt(doc,`${d.windDirection||"—"} · raj. ${n(d.gustKmh,0)}`,x+5,y+34,6,false,C.muted);txt(doc,"ONDA",x+34,y+19,6,true,C.muted);txt(doc,`${n(d.waveHeightM)} m`,x+34,y+28,13,true);txt(doc,`${d.waveDirection||"—"} · ${n(d.wavePeriodS)} s`,x+34,y+34,6,false,C.muted);txt(doc,"CORRENTE",x+5,y+45,6,true,C.violet);txt(doc,`${mph(d.currentKmh)} mph`,x+5,y+54,11,true);const day=weekly.find((w:any)=>w.date===String(d.time||"").slice(0,10));txt(doc,"CLOROFILA",x+34,y+45,6,true,[100,230,170]);txt(doc,`${n(day?.chlorophyllMgM3,2)} mg/m³`,x+34,y+54,10,true)})}footer(doc);return doc}
export function downloadPositionForecastPdf(data:any){const doc=createPositionForecastPdf(data);doc.save(`previsao-oceanica-${new Date().toISOString().slice(0,10)}.pdf`)}
